add API examples and reference docs
plotly/dds-api-docs pull request #1
Opened 2019-03-27 16:45 UTC by briandennis

Adds an example query and reference file for each DDS Query/Mutation.

 Note, contrary to https://github.com/plotly/streambed/issues/12516#issuecomment-468394175, we ended up formatting the reference examples as a query + argument description instead of Python strings. This ended up being as easy to accomplish leveraging existing tooling. Let me know if you'd in fact prefer the Python string references though and we can quick switch it over.

We also included the script we used to generate the reference files. It can be rerun whenever the schema changes to generate fresh references.

Closes https://github.com/plotly/streambed/issues/12516

2019-03-27 17:27 UTC, mfix22 commented on queries/portals/example.py
> +portals_name_query = gql(
@briandennis should we have an example that fetches `apps` under `portals`?

2019-03-27 17:28 UTC, mfix22 commented on mutations/updatePortal/reference.md
> +mutation updatePortal($page: Int, $portalname: String, $metadata: JSONString){
@briandennis are we not including `requireLogin` here?

2019-04-03 20:00 UTC, scjody requested changes
Can you add some documentation on how this all fits together? A toplevel `README.md` would be a good place.
* How do I get started with this if I need to make changes? (installing dependencies, etc?)
* What does `genReferenceDocs.js` do and how should we run it?  

Also can you make sure these scripts have been tested against a DDS instance?

2019-04-03 20:00 UTC, scjody commented on mutations/addApp/example.py
> +print("new app cpu usage: {result.app.analytics.resources[0].cpuUsage}")
This isn't relevant for a new app - the app hasn't been deployed yet, so this will always be zero (or an error)

2019-04-03 20:00 UTC, scjody commented on mutations/addApp/example.py
> +print("new app deploying: {result.app.status.deploying}")
This also won't ever be `True` for a new app.

(I suggest removing these from the example mutation call.)

2019-04-03 20:00 UTC, scjody commented on mutations/removeCollaborators/example.py
> +print("updated first collaborators teams: {result.app.collaborators[0].teams}")
What does "first collaborators" mean here? An app only has one set of users and one set of teams as collaborators.

2019-04-03 20:00 UTC, scjody commented on mutations/updatePortal/example.py
> +        "description": "This is a description for a portals metadata.",
🐐 Would "This is a description for a portal." make more sense here?

2019-04-03 20:00 UTC, scjody commented on mutations/uploadAppThumbnail/example.py
> +result = request.post(dds_endpoint, files=files, data=data).data
Have you tested this example? This doesn't look likely to work to me.

2019-04-03 20:00 UTC, scjody commented on mutations/uploadPortalLogo/example.py
> +result = request.post(dds_endpoint, files=files, data=data).data
Again, this seems unlikely to work.

2019-04-03 20:00 UTC, scjody commented on queries/apps/by_name.py
> +reuslt = dds_client.execute(apps_name_query)
This looks like a typo

2019-04-03 20:00 UTC, scjody commented on queries/apps/by_page.py
> +print("next page: {result.nextPage}")
How does the user retrieve the next page?

2019-04-03 20:00 UTC, scjody commented on queries/current/example.py
> +            username
`isAdmin` is missing here.

2019-04-03 21:05 UTC, mfix22 commented on queries/apps/by_page.py
> +print("next page: {result.nextPage}")
Hey Jody, I'm a little confused about this one. Are you asking how would you access the nextPage value, or how would a user fetch the next page. 

If it is the later, would you like me to add:
```python
apps_page_query = gql(
    """
    {
      apps(page: {result.nextPage}) {
        apps {
            urlOnServer
            metadata {
                showInPortal
            }
        }
        nextPage
      }
    }
    """
)

third_page = dds_client.execute(apps_page_query)
```
to the example?

2019-04-03 22:42 UTC, scjody commented on queries/apps/by_page.py
> +print("next page: {result.nextPage}")
How a user would fetch the next page. If that example works please add it 😸

2019-04-04 01:26 UTC, mfix22 commented
Hey @scjody I made a lot of updates to the examples after testing them further. The examples all work, including the file upload examples. I do need to test updating SSH keys. 

I will update the `README.md` with more information tomorrow 👍

2019-04-04 19:38 UTC, mfix22 commented
Hey @scjody cleaned up a ton of stuff, and I have tested all the examples — it's ready for another round of review 🙂

2019-04-04 21:58 UTC, scjody approved these changes
Thanks for the changes! This looks good to me now, and I think it's worth merging. 💃 

Once it's merged I'll confirm with the documentation team that this meets their needs. Can we keep https://github.com/plotly/streambed/issues/12516 open until I've done that?

2019-04-04 21:58 UTC, scjody commented on README.md
> +These docs contain the reference DDS GraphQL API (found in the `.md` files), as well as runnable Python examples for each query and mutation.
👍

2019-04-04 21:58 UTC, scjody commented on queries/apps/by_page.py
> +third_page = dds_client.execute(apps_page_query, {"page": nextPage})["apps"]
👍

2019-04-04 22:47 UTC, merged